config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :food_items
  get 'menu' => "home#menu"
  get 'contact_us' => "home#contact_us"
  get 'about_us' => "home#about_us"

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
has_many :order_food_items
	def image_url_or_auto
		if image.present?
			image
	else
		"http://loremflickr.com/320/240/#{name}"
		end
	end


	def self.filter_by_section(section)
    	where("section like ?", "%#{section}%")
  	end

  	def self.search(search)
  		where("name like ?","%#{search}%")
  	end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_food_items, dependent: :destroy
  has_many :food_items, through: :order_food_items
end

app/models/order_food_item.rb
class OrderFoodItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order
end

app/models/section.rb
class Section < ApplicationRecord
	validates :name, presence: true, uniqueness: {case_sensitive: false}
	has_many :food_items
	 
	def self.generate_defaults
		%w(Breakfast Lunch Dinner Drinks).each do |name|
			Section.find_or_create_by(name: name)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :price, :description, :image, :section)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def menu
    @food_items = FoodItem.all
  	@sections = %w(Breakfast Lunch Dinner Drinks)
    @food_items = FoodItem.filter_by_section(params[:section]).order("#{params[:sort_param]} ")
  
    if params[:search]
      @food_items = FoodItem.search(params[:search])
    end

  end

  def contact_us
  end

  def about_us
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @selected_food_item = @order.order_food_items.first
  end

  # GET /orders/new
  def new
    
    @order = Order.new
    @selected_food_item = FoodItem.find params[:id]
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.create!(order_params)
    @order.order_food_items.create(quantity: params[:order][:quantity], food_item_id: params[:order][:food_item_id])
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:username, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.text_field :section %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.image %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @food_item.image %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/about_us.html.erb
<br>
<h1>About Us</h1>
<br>
<img src="http://www.lehighvalleymarketplace.com/wp-content/uploads/2016/05/muellers_feature-1110x600.jpg" alt="eddiEATs Korean American Fusion"; style="width:1110px;height:600px;">
<br><br>
<p>We are a very small independent 40-seat restaurant in the heart of Saigon, serving globally inspired cuisine, that we like to call Korean American.  The menu is designed to be shared and dishes are proportionate to ordering a variety of items for the table. Our selections change nightly based on availability and the desire to showcase carefully sourced products at their peak. We strive to update our menu online on a daily basis but what you see on our website may be slightly different than what is being offered that evening. </p>
<br>
<h5>EDDIEATS CREDO</h5>
<br>
<p>Please understand although we strive to serve food and drink with distinction we are still a small independent family run restaurant. No smoke and mirrors here. Just food from the heart. Our space is limited and our staff is small. We believe that we have the ability and resources to make all of our guests happy while dining in our "home" (as we see it). It can get loud in here when we are full but we believe this adds to the convivial atmosphere we provide. We are always happy here and this shows in the spirit of our restaurant.  If you are grumpy, pouty, crabby or just plain mean, this may not be the place for you. We look forward to serving you with all of our hearts and a smile.</p>
<br>
<h5>DIETARY RESTRICTIONS</h5>
<br>
<p>We take allergies seriously and to avoid the potential of product crossover we don't allow for modifications or alterations to any dishes but will be happy to guide you towards items that are suitable to your dietary needs. We strive to keep a balanced menu with offerings for vegetarian and pescetarians alike.</p>
<br>
<h5>KIDS</h5>
<br>
<p>As parents ourselves we advise families with small children to visit us between 5pm - 6pm for a more relaxing experience. We offer a nutritious kids menu that features local produce and meats. There is also a newly updated park with swings and things to play on across the street!</p>
<br>
<h5>BEVERAGE/CORKAGE</h5>
<br>
<p>Our beverage program offers an affordable and exciting wine list along with a few seasonal cocktails & beers. All selections have been carefully chosen to compliment our food. No outside food or beverages allowed. </p>
<br>
<h5>RESERVATIONS/SEATING POLICY</h5>
<br>
<p>Reservations are for seats in the restaurant. As a large portion of our seating is communal, as we strive to make everybody comfortable in our restaurant, having a reservation does not guarantee a private table. </p>
<br>
<p>To be considerate to other guests we may ask for our table back once you have paid your bill if we have a wait list. </p>
<br>
<h5>WALK-INS</h5>
<br>
 <p>We do accept walk-ins on a first come first serve basis. Your party must be complete in order to be seated. For groups of 4 to 6 we do encourage making a reservation. </p>
<br>
<h5>ACCESSIBILITY</h5>
<br>
<p>We are handicapped accessible, we kindly ask to make a note on your reservation so we can offer you a table that best suits your needs.</p>
<br>
<br>

app/views/home/contact_us.html.erb
<br>
<h1>Contact Us</h1>
<br>
<br>
<br>
<div class="row">
	<div class="col-sm-7">
		<address>
		<h5>Address:</h5>
		<br>
		<strong>eddiEATs</strong>
		<br>
		10 Đặng Tất, Tân Định, Quận 1, 
		<br>
		Hồ Chí Minh, Vietnam
		<br>
		<br>
		<br>
		<h5>Telephone:</h5>
		<br>
		0123456789
		</address>
	</div>
	<div class="col-sm-5">
		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15676.956351120589!2d106.6889244!3d10.7929916!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8b18b057ab3b248b!2zQ-G7pWMgR-G6oWNoIFF1w6Fu!5e0!3m2!1sen!2s!4v1476690054293" width="445" height="345" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1 class="display-3">WELCOME TO EDDIEATS!</h1>
	<img src="https://beautifulkalkan.com/wp-content/uploads/2016/06/Post-2.jpg" alt="EDDIEATS"; style="width:1046px;height:336px;">
	<br>
	<p class="lead">Our goal at eddiEATs is to merge the gourmet with the familiar — providing fresh, delicious groceries and prepared foods at approachable prices, with the perks and services of an old-school neighborhood grocer.</p>
	<hr class="m-y-2">
	<p>Come in today or call for a reservation and join us as we cater to you and yours, a fine dining exceptional experience that is rivaled by none.</p>
	<p class="lead">
		<div class="btn-group" data-toggle="buttons">
  			<label class="btn btn-primary btn-lg active">
    	<input type="checkbox" checked autocomplete="off"><a href="/menu"> Menu</a>
  			</label>
  			<label class="btn btn-primary btn-lg active">
    	<input type="checkbox" checked autocomplete="off"><a href="/contact_us"> Contact Us</a>
  			</label>
	</p>
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>
<form class="form-inline">
  <div class="form-group">
   <ul class="nav nav-pills">
  <% @sections.each do |section| %>
    <li class="nav-item">
      <%= link_to section, menu_path(section: section), class: "nav-link #{params[:section] == section && 'active'}" %>
  <% end %>
    </li>
</ul>
  </div>
  <div class="form-group">
    <% @sections.each do |section| %>
    <%=link_to "#{section} Sort By",menu_path(:sort_param => "name",section: section),class: "dropdown-item"%>
    <%end%>
    <% ['price'].each do |column| %>
    <%=link_to "Sort by #{column} ASC",menu_path(:sort_param => "price DESC"),class: "dropdown-item"%>
    <%=link_to "Sort by #{column} DESC",menu_path(:sort_param => "price ASC"),class: "dropdown-item"%>
    <%end%>

</div>
  <div class="card-deck-wrapper">
    <% @food_items.in_groups_of(3, false) do |row| %>
    <div class="card-deck">
    <% row.each do |food_item| %>
      <div class="card">
      <%= image_tag food_item.image_url_or_auto%>
        <div class="card-block">
          <h4 class="card-title"><%= link_to food_item.name, food_item_path(food_item)%></h4>
          <p class="card-text"><%= food_item.description %></p>
        </div>
           <div class="card-footer text-muted">
            <span class="label label-info total-count">
              <%= number_to_currency food_item.price %>
             </span>
      
           <%= link_to 'Order Now', new_order_path(id: food_item.id), class: 'btn btn-primary' %>
          </div>
    </div>
      <% end %>
  </div>
<% end %>
</div>

<script>
$('.dropdown-toggle').dropdown()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EddiEATs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<nav class="navbar navbar-light bg-faded">
  			<a class="navbar-brand" href="/">eddiEATs</a>
  			<ul class="nav navbar-nav">
  				<li class="nav-item active">
              <%= link_to 'Menu', menu_path, class: 'btn btn-default' %>
  				</li>
  				<li class="nav-item">
              <%= link_to 'Contact Us', contact_us_path, class: 'btn btn-default' %>
  				</li>
          <li class="nav-item">
              <%= link_to 'About Us', about_us_path, class: 'btn btn-default' %>
          </li>          
  			</ul>
  			<form class="form-inline pull-xs-right">
      <%= text_field_tag :search, params[:search], class: "form-control",placeholder: "Search" %>
      <button class="btn btn-success-outline" type="submit">Search</button>
    </form>
  		</nav>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="col-md-5">

<div class="card">

<div class="container">
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.hidden_field :food_item_id, :value => @selected_food_item.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>
  </div>

</div>

</div>

<div class="col-md-4" id="sidebar" style="float: right">
<div class="card">
  <div class="card-block">
    <h4 class="card-title" style="text-align:center"><%= @selected_food_item.name %></h4>
  </div>
  <%=  image_tag @selected_food_item.image_url_or_auto %>
  <div class="card-block">
    <p class="card-text" style="text-align:center"><%= @selected_food_item.description %></p>
    <p class="card-text" style="text-align:center"><span class="label label-info total-count">
      <%= number_to_currency @selected_food_item.price %>
      </span>
    </p>
  </div>
</div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.username %></td>
        <td><%= order.phone %></td>
        <td><%= order.address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Thank you for Your Order</h1>
<div class="wrap">

<div class="card">
  <div class="card-block">
    <h4 class="card-title" style="text-align:center">   <strong>Username:</strong> <%= @order.username %></h4>
    <p class="card-text" style="text-align:center">  <strong>Phone:</strong><%= @order.phone %></p>
    <p class="card-text" style="text-align:center">  <strong>Address:</strong><%= @order.address %></p>
  </div>
  <%= image_tag @selected_food_item.food_item.image_url_or_auto %>
  <div class="card-block">
    <p class="card-text" style="text-align:center"><%= @selected_food_item.food_item.name %></p>
    <p class="card-text" style="text-align:center"><%= @selected_food_item.food_item.description %></p>
    <p class="card-text" style="text-align:center"><span class="label label-info total-count">
              <%= number_to_currency @selected_food_item.food_item.price + 20000 %>
             </span>
    <p class="card-text" style="text-align:center"><span class="label label-info total-count">
      <%= @selected_food_item.food_item.created_at.strftime("Created on: %d %b %y at %I:%M%p") %>
  </div>
</div>
</div>